[project]
name = "rent-vs-buy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "streamlit>=1.48.1",
    "watchdog>=6.0.0",
]
